services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - docker_compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: datajud-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8009:80
    env_file:
      - .env
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8009
    networks:
      - docker_compose
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  docker_compose:
    driver: bridge
